### ISSUE TITLE
Attempting to compile rust-teos watchtower plugin fails.

### ISSUE THREAD

**Issue by unsettledroell404** [talaia-labs/rust-teos#115]
I am trying to compile the CLN plugin for TEOS on an Intel NUC and it fails with the following error.

...
Compiling bitcoin v0.28.1
Compiling teos-common v0.0.1 (/data/cln/plugins-available/rust-teos/teos-common)
Compiling hyper-timeout v0.4.1
error: failed to run custom build command for `teos-common v0.0.1 (/data/cln/plugins-available/rust-teos/teos-common)`

Caused by:
  process didn't exit successfully: `/data/cln/plugins-available/rust-teos/target/release/build/teos-common-a198ce27a137d37e/build-script-build` (exit status: 1)
  --- stderr
  error running rustfmt: Os { code: 2, kind: NotFound, message: "No such file or directory" }
warning: build failed, waiting for other jobs to finish...
error: failed to compile `watchtower-plugin v0.1.0 (/data/cln/plugins-available/rust-teos/watchtower-plugin)`, intermediate artifacts can be found at `/data/cln/plugins-available/rust-teos/target`

Caused by:
  build failed

**Comment by unsettledroell404** [comment]
OK the solution was simpler than I thougt, rustfmt must be installed (apt install rustfmt).

**Comment by meryacine** [comment]
> OK the solution was simpler than I thougt, rustfmt must be installed (apt install rustfmt).

Aha, this is due to `tonic-build`'s dependency on `rustfmt`. This was fixed in [this PR (landed in v0.7)](https://github.com/hyperium/tonic/pull/904).
