### ISSUE TITLE
Implement periodic retries 

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/rust-teos#137]
It would be nice to make `watchtower-plugin` periodically retry unteachable towers so appointments don't pile up if the user does not realize the tower may have been unreachable for a while.

**Comment by 3cola** [comment]
while waiting for this new awesome feature, as a temporary solution ?,  one can run this dirty periodic task via a cron :
`lightning-cli listtowers | jq -r 'to_entries | map(.value += {id:.key} | .value) | map(select(.status=="unreachable"))[] | .id ' | xargs -I % lightning-cli retrytower %`
