### ISSUE TITLE
Add onion address on get_tower_info

### ISSUE THREAD

**Issue by jochemin** [talaia-labs/rust-teos#143]
You may need your onion address time after starting your tower, the only time it's showed is when you start it.

IMO it would be nice to have the address on get_tower_info output.

**Comment by sr-gi** [comment]
Agreed, we can actually add both the `clearnet` and `tor` interfaces to a new section in `get_tower_info` (called interfaces maybe)?

**Comment by mariocynicys** [comment]
@sr-gi 

From https://community.torproject.org/onion-services/setup/ (Step 2: Configure your Tor Onion Service)
> `HiddenServicePort 80 127.0.0.1:80`
The `HiddenServicePort` line specifies a virtual port (that is, the port that people visiting your Onion Service will be using), and in the above case it says that any traffic incoming to port 80 of your Onion Service should be redirected to 127.0.0.1:80 (which is where the web server from step 1 is listening).

I guess onion ports doesn't conflict with real ports then.

**Comment by sr-gi** [comment]
> @sr-gi
> 
> From https://community.torproject.org/onion-services/setup/ (Step 2: Configure your Tor Onion Service)
> 
> > `HiddenServicePort 80 127.0.0.1:80`
> > The `HiddenServicePort` line specifies a virtual port (that is, the port that people visiting your Onion Service will be using), and in the above case it says that any traffic incoming to port 80 of your Onion Service should be redirected to 127.0.0.1:80 (which is where the web server from step 1 is listening).
> 
> I guess onion ports doesn't conflict with real ports then.

Just tested this out. Looks like it does work indeed. Nice catch!

Given the HS is currently handled by `tor.rs` we don't need to specify anything in `torrc`, just change the default port to `9814` to match the default API.

**Comment by sr-gi** [comment]
It'll be nice double test this though. Can you give it a go @mariocynicys?

```
diff --git a/teos/src/config.rs b/teos/src/config.rs
index 6142513..86ab07b 100644
--- a/teos/src/config.rs
+++ b/teos/src/config.rs
@@ -257,7 +257,7 @@ impl Default for Config {
             api_port: 9814,
             tor_support: false,
             tor_control_port: 9051,
-            onion_hidden_service_port: 2121,
+            onion_hidden_service_port: 9814,
             rpc_bind: "127.0.0.1".into(),
             rpc_port: 8814,
             btc_network: "mainnet".into(),
```

**Comment by mariocynicys** [comment]
> It'll be nice double test this though. Can you give it a go @mariocynicys?

Sure.
> Given the HS is currently handled by tor.rs we don't need to specify anything in torrc, just change the default port to 9814 to match the default API.

What's HS?
@sr-gi

**Comment by mariocynicys** [comment]
@sr-gi Confirmed. Both interfaces can work on the same port simultaneously.

**Comment by sr-gi** [comment]
> > It'll be nice double test this though. Can you give it a go @mariocynicys?
> 
> Sure.
> 
> > Given the HS is currently handled by tor.rs we don't need to specify anything in torrc, just change the default port to 9814 to match the default API.
> 
> What's HS? @sr-gi

I meant hidden service
