### ISSUE TITLE
Re-enable teosd startup check for watchtower-plugin tests

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/rust-teos#156]
https://github.com/talaia-labs/rust-teos/pull/153 disabled a check in the `watchtower-plugin` to wait for `teosd` startup. This is because after updating both `cln` and `pyln-testing` the check started to fail. 

It looks like this is due to how the `TailableProc` checks for the logs, and it happens, especially, if the process is stopped and re-started. I tried to make the `TailableProc` re-init, so the logs and the offset are reset (which seemed to be a step in the right direction). This made the tests work but randomly fail sometimes.

Given #153 is blocking some issues / other PRs, and removing the check makes the tests pass (they may still randomly fail if the process happens to not have started by the time the tests are run though) I think it is worth disabling for now.

Do a proper investigation of why this is failing and fix it.

**Comment by mariocynicys** [comment]
May this be due to logs not being flushed early enough?

**Comment by sr-gi** [comment]
> May this be due to logs not being flushed early enough?

I'm not really sure tbh. Take a look at my WIP fix if you feel like it and you'll see it does not seem to be like that, because even that solution randomly fails.

**Comment by mariocynicys** [comment]
> I'm not really sure tbh. Take a look at my WIP fix if you feel like it and you'll see it does not seem to be like that, because even that solution randomly fails.

Well, the WIP code does somewhat assert my claim (right?). It fails randomly not based on whether it's re-initted or not, which might be due to stdout buffers not being flushed early.

But I visited the source of simple_logger crate and pyln.testing and this seems indeed not to be the case.

Will have to install lightningd and run the tests manually.

**Comment by sr-gi** [comment]
I'll also put more time into properly testing this, but I think other features may be worth prioritizing more at the moment, like fixing the blocked issues in https://github.com/talaia-labs/rust-teos/discussions/102 (that were unblocked after `cln-plugin=0.1.1) and adding `auto-register` and `auto-retry` to the `watchtower-plugin`

**Comment by mariocynicys** [comment]
Cool I will take on some of them then. :+1:

**Comment by sr-gi** [comment]
As expected, removing the check makes test also randomly fail.

https://github.com/talaia-labs/rust-teos/actions/runs/3534308802/jobs/5931197578

**Comment by mariocynicys** [comment]
Also notice it was canceled by github infra cuz the test took so long. So this kinda looks like a tower doesn't start issue and not a log doesn't write issue.

**Comment by sr-gi** [comment]
The log checks are removed here, it may be that the checks were done before the tower started, so the test ended up on a iffy state.
