### ISSUE TITLE
Remove pending_appointments sanity check in `Retrier::run`

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/rust-teos#159]
This feels unnecessary given the rest of the code is run only if there are pending appointment

https://github.com/talaia-labs/rust-teos/blob/c14c7364fd42a3f2f3ba587b1bf509e51f95aa18/watchtower-plugin/src/retrier.rs#L238-L241

The only real interface change would be the returning value being `Ok(())` instead of an error stating that there are no pending appointments. Such an error may make sense if, logically, there was a reason to send a job to the retrier with no pending appointments. However, I don't think such a case exists (that condition should never verify).

Thoughts @mariocynicys?

**Comment by mariocynicys** [comment]
yeah this should not really ever happen.
the last time we check for pending appointments at `should_start` and after it the retrier hasn't started yet till this check so nothing really should change in this period.

we can return `Ok(())` here, or even better remove the check all together and the method will return `Ok(())` anyways if this case happens (which I'm sure it never will).

**Comment by sr-gi** [comment]
Agreed
