### ISSUE TITLE
Create a ping endpoint for the tower

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/rust-teos#180]
Having an easy way of knowing whether a tower is online without having to send any meaningful data may be useful.

Currently, the only ways that come to mind (for registered towers) are either requesting something or re-registering.

**Comment by sr-gi** [comment]
Thoughts @mariocynicys?

**Comment by mariocynicys** [comment]
Yup would be cool to have a ping pong message similar the one used in LN.

**Comment by iamhardikat11** [comment]
Hi, Can i take up this Issue?

**Comment by mariocynicys** [comment]
Hey @iamhardikat11 ,
Sure you can take a look at it and tell what you think.
If you wanna try adding a new http endpoint you might wanna look in `teos/src/api/http.rs` or in [here](https://github.com/talaia-labs/rust-teos/blob/076c9729130aa78ae90f2b2b2c5b3b7e338791a1/teos/src/api/http.rs#L220) specifically.

**Comment by sr-gi** [comment]
> Hi, Can i take up this Issue?

Sure thing!

**Comment by anmode** [comment]
Hi i created the endpoint just testing it. Could i generate pR??

**Comment by sr-gi** [comment]
> Hi i created the endpoint just testing it. Could i generate pR??

Sure, you don't need to ask permission for that 😉
