### ISSUE TITLE
`gettowerinfo` returns wrong port for `torv3` addresses

### ISSUE THREAD

**Issue by mariocynicys** [talaia-labs/rust-teos#186]
In my local config, Tor runs on port 9513:
```
onion_hidden_service_port = 9513
```

But when running `teos-cli gettowerinfo`, it returns:
![image](https://user-images.githubusercontent.com/56920956/215349099-b381bff3-c3c9-490d-bf89-1fac82eb97e3.png)

Note that the tower's http interface run on port `9512` in my config.

**Comment by mariocynicys** [comment]
Here is where we record Tor's address information after starting the interface.
https://github.com/talaia-labs/rust-teos/blob/4ce986e0bef0fb90aa6d9b7a74656422a68f4f1d/teos/src/main.rs#L294-L297

**Comment by 1010adigupta** [comment]
Hey I am participating in Summer of Bitcoin, proposal round is yet to be started, for now I want to take up this issue.

**Comment by sr-gi** [comment]
Hey @1010adigupta, great to have you around.

Feel free to try to fix this and ping us if you have any questions. I've been out for a few days but should be back on Monday.

**Comment by 1010adigupta** [comment]
yeah great, sure sure, you can assign me this issue.

**Comment by sr-gi** [comment]
Hey @1010adigupta, this is the last blocking bit for v0.2.0 release (no pressure 🤣), do you think you'll manage to fix it in the next day or two?

Otherwise, we can assign you any other `Good first issue` and fix this one ourselves so the code can be released.

**Comment by 1010adigupta** [comment]
Hey you can assign me another good first issue, it would be better not to delay the release.
