### ISSUE TITLE
Add support for rpccookiefile in teos.toml

### ISSUE THREAD

**Issue by d6n13l0l1v3r** [talaia-labs/rust-teos#246]
Description

In order to avoid username/passwords which are not the recommended config for bitcoind it would be great if i could import the rpccookiefile for bitcoind instead of using user/pass

Problem to be solved

corelíghthing, fulcrum , electrs, and most other tools i use utilize the cookie file to avoid using a static user:pass, but I'm unable to use rust-toes with this configuration because it appears as though there is no support for the cookie file

Proposed solution

allow rust-toes to use the cookie file for bitcoind rpc authentication

**Comment by sr-gi** [comment]
I looked at this and realized it may easily fixable than I initially thought. I'm wondering how the config looks in the other services you mention. Do you simply specify either user/pass or the file path, or does it default to use the cookie if the user/pass is not provided?

**Comment by d6n13l0l1v3r** [comment]
You only specify the path for cookie file 
Example 

/data/bitcoin/.cookie

**Comment by d6n13l0l1v3r** [comment]
I don't know if you can see this as reference  https://github.com/golden-guy/ckpool-solo/commit/3df23a6f4335591fc6f48de394d1b16df995dbdd

**Comment by sr-gi** [comment]
@d6n13l0l1v3r would you mind giving https://github.com/talaia-labs/rust-teos/pull/249 a go? The final version may slightly vary due to code review, but I'd like to know if this has the expected UX

**Comment by sr-gi** [comment]
You can test it by creating a separate branch and pulling from the PR branch:

```
git checkout -b rpcauth-patch
git pull https://github.com/sr-gi/rust-teos.git 2024-01-authcookie
```

**Comment by d6n13l0l1v3r** [comment]
on it 

<img width="898" alt="image" src="https://github.com/talaia-labs/rust-teos/assets/25048143/85f2e3be-7a94-4cf3-8a2b-948267acd1fb">

<img width="1246" alt="image" src="https://github.com/talaia-labs/rust-teos/assets/25048143/c4eed0c9-0442-48db-b01e-f1d780e62245">


I comment the user and password to test btc_rpc_cookie 

<img width="381" alt="image" src="https://github.com/talaia-labs/rust-teos/assets/25048143/d2546c8c-d9e2-4e59-8f15-3d30c8545be5">

start daemon 

<img width="1217" alt="image" src="https://github.com/talaia-labs/rust-teos/assets/25048143/35e6a38c-6cfb-4a65-aa4f-90f98aba1b38">


until now all looks fine

![image](https://github.com/talaia-labs/rust-teos/assets/25048143/d5d7d139-2f3e-4571-b91c-5773d5ab2fc7)

confirm that after one new block arrive teos receive it as expect 

for me the change is ok

**Comment by mariocynicys** [comment]
Let's keep this open until #249 is merged.

**Comment by 0xSaksham** [comment]
I would like to work on this.

**Comment by sr-gi** [comment]
> I would like to work on this.

Check the linked PR. This has already been addressed, it just needs merging
