### ISSUE TITLE
DBM insert statements can be simplified using rusqlite::Statement::insert

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/rust-teos#63]
This may be irrelevant though, given @SpoonBuoy is working or reworking all the DBM logic.

Leaving it here as a note just in case it ends up being relevant.

**Comment by SpoonBuoy** [comment]
I don't think it will be required now, since we are removing the dependency of rusqlite as you suggested to use sqlx instead.

**Comment by meryacine** [comment]
I just took a look at sqlx. Nice project, but I think it's a bit low level than what we need here. An ORM would do nice and keep things clean.
I'm thinking about one of these:
- [SeaORM](https://www.sea-ql.org/SeaORM/)
- [Diesel](https://diesel.rs/)

Would like to here your opinion.

**Comment by SpoonBuoy** [comment]
Yeah, an ORM like SeaORM would handle lot of edges that we would have to take care of using sqlx like (making two different queries for sqlite and postgres in some cases), thus making code much cleaner and non repetitive.

**Comment by sr-gi** [comment]
I'm just personally not a big fan of ORM, but it's ultimately on you @SpoonBuoy. If you rather go with one of the ORM options I won't complain. It's your project at the end of the day.

**Comment by SpoonBuoy** [comment]
I had already implemented _users_ related functions with sqlx, but I think ORM is a better option as @meryacine mentioned. Would start working on an altogether new dbm with SeaORM. Have to hurry up a little since I have to submit mid-term report by the end of this month.
