### ISSUE TITLE
Use GH Actions caches to reduce CI run times

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/rust-teos#66]
Run times for CI jobs in GH Actions will drastically increase after merging #65. The main reason is twofold:

- First, `cln` needs to be compiled from source to run the tests, given it needs to be configured with developer flags.
- Second, the tests use `teosd`, so it needs to be installed in the system (`cargo install`).

This adds almost twice as much time to run CI checks (~10min -> ~20min).

We could try to use caches to store the compiled `cln` binaries and see if we can also store a cache from the `cargo build` of `teos` from the previous CI jobs. That way we could link the debug `teos` binaries and we won't need to install them from scratch.

**Comment by meryacine** [comment]
hmmm, I tested tried the `cln plugin` on my system and didn't need to enable `cln`'s developer flags.
Did this type of dependency come from the E2E tests?

**Comment by sr-gi** [comment]
@meryacine yes, the E2E test use the `dev_sign_last_tx` cln rpc command, which is only available if compiled with dev flags.

**Comment by sr-gi** [comment]
Closed by #65
