### ISSUE TITLE
Auto renew subscriptions

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/rust-teos#69]
It may be nice to have an `--autorenew` subscription flag for the register message so the client does auto-register with the tower if it gets out of appointments, especially if the tower is offering the subscription altruistically.

Currently, if the subscription expires and the user does not realize, pending appointments may start to pile up and waste user resources.

**Comment by sr-gi** [comment]
Turns out CoreLN does not support options, only positional (or named) parameters.

**Comment by 3cola** [comment]
I know this is not a solution but I have this command running in a cron to autorenew, if that helps someone:
`lightning-cli listtowers | jq -r 'to_entries | map(.value += {id:.key} | .value) | map(select(.available_slots<1000))[] | [ .id + "@" + .net_addr|sub("http://";"")|s
ub("https://";"")] | @tsv' | xargs lightning-cli registertower`

**Comment by sr-gi** [comment]
@3cola that's actually pretty cool. There is an open PR adding this functionality to the plugin though 😁

https://github.com/talaia-labs/rust-teos/pull/164

**Comment by sr-gi** [comment]
Closed via #164

**Comment by sr-gi** [comment]
Closed via https://github.com/talaia-labs/rust-teos/pull/164
