### ISSUE TITLE
Persist tor private key

### ISSUE THREAD

**Issue by meryacine** [talaia-labs/rust-teos#70]
ATM, the tower creates a new onion service id upon restarts.
We better store the onion private key and restore it when the tower is started to keep the same ID.

**Comment by sr-gi** [comment]
Thoughts on this @tee8z?

**Comment by meryacine** [comment]
This is how bitcoind handles it. Caches it in the data dir.
![image](https://user-images.githubusercontent.com/56920956/177332632-31d3c8e0-d741-498f-8732-54bcfaf707c4.png)

**Comment by sr-gi** [comment]
@meryacine I like that approach!
