### ISSUE TITLE
Sqlite error with watchtower-client

### ISSUE THREAD

**Issue by CMDRZOD** [talaia-labs/rust-teos#91]
Trying to install and run the latest release. I've built on my intel PC using Ubuntu 22.04

I am getting this error after adding the plugin to c-lightning:
plugin-manager: started(3360577) /home/hair/.cargo/bin/watchtower-client
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such column: rr.subscription_start"))', watchtower-plugin/src/dbm.rs:260:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Is there a file I must remove after running the beta release?

**Comment by meryacine** [comment]
> Is there a file I must remove after running the beta release?

Yes, it's `WATCHTOWERPLUGIN_DATADIR/watchtowers_db.sql3` (which is probably `/home/hair/.watchtower/watchtowers_db.sql3` on your system).
The breaking change was introduced in #77. You will need to update the tower daemon too if you haven't already.

**Comment by CMDRZOD** [comment]
This was the fix. Thank you.
